dist: bionic
language: php

php:
- 8.1
- 8.2

env:
  global:
  - SETUP=stable
  matrix:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

cache:
  directories:
  - $HOME/.composer/cache

install:
- if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
- if [[ $SETUP = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false
  slack:
    rooms:
    - secure: hxkdweDwWWcXs0cnlSnlZXW8CzXaddAddDnvapLxDOB9XN3rDcrQgKncBjRqOIC7D+aqpTMvRBtfoKcnUIorXRhaTQat9l7/CL3fJs/zsLUz+RHbK9e9Daep22L/yM5ucn3EwQT/95xb6fnUycdTpfnUaFiYXt/IYCyyg4nnIHEo27Cv4ePpaKcRgc03P496pHqIb3iMfduQLufte9eF/Tqf5OfdlWjC89icri2l2Or6iIZNA/7T022jEQwZ+ZqaMV8zQqQFUOQy6DRGluPCWGn1GLC+cZihqToowMrTk0or64PZ0i/mInSdSOTCPi//fg/f56RGBqsB1mH6U+0zxvmSbfNEVfGyzg63/QGl1TN2zhY86cpKUkAos8g7ZqcaOs97YZplBXaN7kZD0LTeyHnlZ//pqIOkebUivVkZeTd3GZTX1lrg6ZpOkYBWNVIThHql04A9DfLDbPfj5r/fOvsXTuep1FkHhGS1q6gWVYJnSmxem/1U97DrOQwpESL7p068ZDjwbIh5b5qU2jCMgsfxKtvnP+jMGrFEI7Erw18zb9liShr16YE9UqyTyplrq7V/WVQyf9pqy6sR4NzQa5aNd0q4Ei1MLq69p/tUpjnaP2Oss/ocM4UayBZ7upCPE9BDGWqHJxmfvn9bro6sDMKKGPEnewZqo/yBx5697fQ=
